spring.datasource.url=jdbc:postgresql://localhost:5432/game_db
spring.datasource.username=postgres
spring.datasource.password=1mW0rk1ng

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true