spring.datasource.url=jdbc:postgresql://localhost:5432/game_db
spring.datasource.username=gamedata
spring.datasource.password=gameDataPass

spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=true